### PR TITLE
StakingEscrow: handling special case when staker is SAFT + university

### PR DESCRIPTION
**Pull request by vzotova**

### CODE REVIEW

**Review by manumonti — APPROVED** [review]
LGTM ✌️

**Review by theref — APPROVED** [review]

**Comment by cygnusv** [comment]
For context, last upgrade introduced a minor bug that affected a single staker, whose substake configuration was an edge case we didn't consider. Said upgrade wrongfully locks an amount, which this changeset fixes on an individual basis, for the sake of simplicity and transparency.

**Review by derekpierre — COMMENTED** [review]
So just to be clear, this change ensures that the staker at the specific address does a cliff vesting (all tokens unlocked) at the original timestamp, as opposed to continuous vesting over time.

**Comment by vzotova** [comment]
> So just to be clear, this change ensures that the staker at the specific address does a cliff vesting (all tokens unlocked) at the original timestamp, as opposed to continuous vesting over time?

These changes add another cliff, second one. First one is when `releaseTimestap == block.timestamp` then all tokens unlocked. before this - only specified value for affected staker

**Comment by cygnusv** [comment]
> So just to be clear, this change ensures that the staker at the specific address does a cliff vesting (all tokens unlocked) at the original timestamp, as opposed to continuous vesting over time?

This staker had a combination of a 2-year linear vesting and a 3-year cliff vesting. The upgrade transformed everything to the latter. Now that the linear vesting is ended, this fix simply reintroduces the original 3-year cliff vesting, so the remaining is assumed to be unlocked.

**Review by derekpierre — APPROVED** [review]
🎸

**Pull request merged**
